version: "3"

services:

  js-express:
    build:
      context: ../.
      dockerfile: Dockerfile
    container_name: express-svc
    hostname: express-svc
    ports:
      - 8081:8081
    expose:
      - 8081
    command: ["node", "express-http-test.js"]
    depends_on:
      - otelcol

  js-http:
    build:
      context: ../.
      dockerfile: Dockerfile
    container_name: js-http
    hostname: js-http
    command: ["node", "http-test.js"]
    depends_on:
      - otelcol

  otelcol:
    image: public.ecr.aws/sumologic/opentelemetry-collector:0.19.2-sumo
    container_name: otelcol
    hostname: otelcol
    command: ["--config=/etc/config.yaml"]
    volumes:
        - ./otelcol.yaml:/etc/config.yaml
    ports:
      - 6831:6831
      - 14250:14250
      - 4317:4317
      - 55680:55680
      - 55681:55681
      - 14268:14268
      - 9411:9411
#    expose:
#      - 4317
#      - 55681
