version: "3"

services:

  express-server:
    build:
      context: ./contactserver
      dockerfile: Dockerfile
    container_name: express-server
    hostname: express-server
    environment:
      - SUMO_HTTP_TRACES_URL=${SUMO_HTTP_TRACES_URL}
    ports:
      - 8081:8081
    expose:
      - 8081
    command: ["node", "express-http-test.js"]
    restart: always

  rum-web:
    build:
      context: ./contactmanager
      dockerfile: Dockerfile
    container_name: rum-web
    environment:
      - REACT_APP_COLLECTION_SOURCE_URL=${REACT_APP_COLLECTION_SOURCE_URL}
    hostname: rum-web
    command: ["npm", "run", "start"]
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - express-server