version: "3"

services:

  golang-simple-service:
    build:
      context: ../.
      dockerfile: Dockerfile
    container_name: simple-service
    hostname: simple-service
    command: ["cmd/simple-service"]
    environment:
      - OTEL_RESOURCE_ATTRIBUTES=service.name=golang-test,application=simple-service-app
    depends_on:
      - otelcol

  otelcol:
    image: public.ecr.aws/sumologic/opentelemetry-collector:0.25.0-sumo-1
    container_name: otelcol
    hostname: otelcol
    command: ["--config=/etc/config.yaml"]
    volumes:
        - ./otelcol.yaml:/etc/config.yaml
    ports:
      - 6831:6831
      - 14250:14250
      - 4317:4317
      - 55680:55680
      - 55681:55681
      - 14268:14268
      - 9411:9411
