AWSTemplateFormatVersion: 2010-09-09
Description: 'Template to install Sumo Logic OTel Distro Collector on ECS in Fargate mode'
Parameters:
  IAMTaskRole:
    Description: Task attached IAM role
    Type: String
    Default: SumoLogicOtelDistroCollectorTaskRoleECSFargate
    ConstraintDescription: must be an existing IAM role which will be attached to EC2 instance.
  IAMExecutionRole:
    Description: Task Execution attached IAM role
    Type: String
    Default: SumoLogicOtelDistroCollectorExecutionRoleECSFargate
    ConstraintDescription: must be an existing IAM role which will be attached to EC2 instance.
  IAMPolicy:
    Description: IAM Role attached IAM Policy
    Type: String
    Default: SumoLogicOtelDistroCollectorPolicyECSFargate
    ConstraintDescription: Must be an existing IAM Managed Policy which will be attached to IAM Role.
  ClusterName:
    Type: String
    Description: Enter the name of your ECS cluster from which you want to collect telemetry data
  SecurityGroups:
    Type: CommaDelimitedList
    Description: The list of SecurityGroupIds in your Virtual Private Cloud (VPC)
  Subnets:
    Type: CommaDelimitedList
    Description: The list of Subnets in your Virtual Private Cloud (VPC)
  SumologicReplicaServiceName:
    Type: String
    Default: sumologic-otel-distro-collector-svc-fargate
    Description: ECS Service Name
  OtlpHttpEndpoint:
    Type: String
    Description: OTLP HTTP Traces Endpoint
  SumologicOtelDistroConfigCollectorParameterName:
    Type: String
    Default: sumologic-otel-distro-config-collector-fargate
    Description: OTel Distro Configuration Parameter Name
Resources:
  ECSTaskDefinition:
    Type: 'AWS::ECS::TaskDefinition'
    Properties:
      Family: sumologic-otel-distro-collector-awsvpc-fargate
      TaskRoleArn: !Sub 'arn:aws:iam::${AWS::AccountId}:role/${IAMTaskRole}'
      ExecutionRoleArn: !Sub 'arn:aws:iam::${AWS::AccountId}:role/${IAMExecutionRole}'
      NetworkMode: awsvpc
      ContainerDefinitions:
        - LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-create-group: 'True'
              awslogs-group: /ecs/sumologic-otel-distro
              awslogs-region: !Ref 'AWS::Region'
              awslogs-stream-prefix: ecs
          Image: public.ecr.aws/sumologic/sumologic-otel-collector:0.52.0-sumo-1
          Name: sumologic-otel-collector
          Command:
            - --config=env:OTEL_DISTRO_CONFIG
          Secrets:
            - Name: "OTEL_DISTRO_CONFIG"
              ValueFrom: !Sub "arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/${SumologicOtelDistroConfigCollectorParameterName}"
      RequiresCompatibilities:
        - FARGATE
      Cpu: 1024
      Memory: 2048
    DependsOn:
      - ECSTaskRole
      - ECSExecutionRole
      - ECSFargateSumologicOtelDistroConfigParam

  ECSFargateSumologicOtelDistroConfigParam:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Ref SumologicOtelDistroConfigCollectorParameterName
      Type: String
      Value: !Sub
        - |
          extensions:
            health_check:
          receivers:
            otlp:
              protocols:
                grpc:
                http:
          processors:
            batch:
              timeout: 5s
              send_batch_size: 256
            # Provides backpressure mechanism. See
            # https://github.com/open-telemetry/opentelemetry-collector/tree/main/processor/memorylimiterprocessor for details
            memory_limiter:
              check_interval: 1s
              limit_mib: 1500
              spike_limit_mib: 800
            # See examples on how to configure cascading filter
            # https://github.com/SumoLogic/sumologic-otel-collector/tree/main/pkg/processor/cascadingfilterprocessor#examples
            cascading_filter:
          exporters:
            otlphttp:
              endpoint: ${OtlpHttpEndpoint}
            logging:
          service:
            extensions: [health_check]
            pipelines:
              traces:
                receivers: [otlp]
                processors: [memory_limiter, cascading_filter, batch]
                exporters: [otlphttp]
        - OtlpHttpEndpoint: !Ref OtlpHttpEndpoint
      Description: OTel Distro Configuration

  ECSReplicaService:
    Type: 'AWS::ECS::Service'
    Properties:
      TaskDefinition: !Ref ECSTaskDefinition
      Cluster: !Ref ClusterName
      LaunchType: FARGATE
      SchedulingStrategy: REPLICA
      DesiredCount: 1
      ServiceName: !Ref SumologicReplicaServiceName
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          SecurityGroups: !Ref SecurityGroups
          Subnets: !Ref Subnets

  ECSTaskRole:
    Type: 'AWS::IAM::Role'
    Properties:
      Description: Allows ECS tasks to call AWS services on your behalf.
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: 'sts:AssumeRole'
      Policies:
        - PolicyName: !Ref IAMPolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - 'logs:PutLogEvents'
                  - 'logs:CreateLogGroup'
                  - 'logs:CreateLogStream'
                  - 'logs:DescribeLogStreams'
                  - 'logs:DescribeLogGroups'
                  - 'ssm:GetParameters'
                Resource: '*'
      RoleName: !Ref IAMTaskRole

  ECSExecutionRole:
    Type: 'AWS::IAM::Role'
    Properties:
      Description: >-
        Allows ECS container agent makes calls to the Amazon ECS API on your
        behalf.
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: ''
            Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: 'sts:AssumeRole'
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy'
        - 'arn:aws:iam::aws:policy/CloudWatchLogsFullAccess'
        - 'arn:aws:iam::aws:policy/AmazonSSMReadOnlyAccess'
      RoleName: !Ref IAMExecutionRole
